[package]
name = "intero-server-api-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
progenitor = "0.14.0"
progenitor-client = "0.14.0"
progenitor-macro = "0.14.0"
reqwest = { version = "0.13.1", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.17"
uuid = { version = "1.18.1", features = ["serde"] }

[lints]
workspace = true
