CREATE ROLE intero_app
  LOGIN
  PASSWORD 'intero_app'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOBYPASSRLS;

CREATE ROLE intero_worker
  LOGIN
  PASSWORD 'intero_worker'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOBYPASSRLS;

GRANT CONNECT ON DATABASE intero TO intero_app;
GRANT CONNECT, CREATE ON DATABASE intero TO intero_worker;
GRANT USAGE ON SCHEMA public TO intero_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO intero_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO intero_app;
